on: push
name: 🚀 Deploy API Engine on push
jobs:
  api-engine-deploy:
    name: 🎉 Private Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: Composer install
      run: composer update
    - name: Add Time Stamp
      run: date > published.txt
    - name: 📂 Private Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: holydemo.com
        username: u483864572.holydemo_ftp_admin
        password: ${{secrets.FTP_PASSWORD}}
        port: 21
        server-dir : / 
        exclude: |
          **/.git*
          **/.git*/**
          **/public_html/**
          **/storage/**
          **/vendor/**
          **/.env*



